credentials:
  valid_username: standard_user
  valid_password: secret_sauce
  leading_whitespace_username:  standard_user
  invalid_username: invalid_user
  invalid_password: invalid_password
  special_characters_username: $£"*&(!%)
  sql_injection: "' OR '1'='1' -- "
  long_username: verylongusernamefortestingpurposeonlythatshouldfail
  long_password: verylongpasswordfortestingpurposeonlythatshouldfail
