name: Python UI Tests with Allure

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run tests with pytest and generate allure results
      run: |
        pytest --alluredir=allure-results

    - name: Upload allure results as artifact
      uses: actions/upload-artifact@v4@b4b3f0d3a6dbb82c45b8c1aafffffb88cb43adbd
      with:
        name: allure-results
        path: allure-results
      continue-on-error: true


